<?php
$labels = array();
$labels['aliases'] = 'Aliases';
$labels['autoreply'] = "Enviar una notificaci&oacute;n";
$labels['autoreplybutton'] = 'Guardar';
$labels['autoreplymessage'] = 'Mensaje de autorespuesta';
$labels['autoreplysubject'] = 'Asunto de autorespuesta';
$labels['failed'] = 'Fall&oacute; el cambio de vacaciones!';
$labels['forward'] = 'Configuraciones de reenvio';
$labels['forwardingaddresses'] = 'Reenviar el correo hacia';
$labels['keepcopy'] = 'Guardar una copia del correo';
$labels['mailforward'] = 'Reenvio de correo';
$labels['outofoffice'] = 'Notificacion de vacaciones (Fuera de la Oficina)';
$labels['separate_alias'] = 'Separate each alias address by a comma';
$labels['separate_forward'] = 'Searate each forward address by a comma';
$labels['success_changed'] = 'Configuraciones de vacaciones cambiadas satisfactoriamente';
$labels['vacation'] = 'Vacaciones';
// Button text
$labels['aliasesbutton'] = 'Get aliases';
?>
