<?php
$labels = array();
$labels['aliases'] = 'Alias';
$labels['autoreply'] = 'Activer la réponse automatique';
$labels['autoreplybutton'] = 'Sauvegarder';
$labels['autoreplymessage'] = 'Contenu du mail de réponse automatique';
$labels['autoreplysubject'] = 'Sujet du mail de réponse automatique';
$labels['failed'] = 'Erreur de configuration';
$labels['forward'] = 'Configuration du transfert';
$labels['forwardingaddresses'] = 'Transférer le mail à';
$labels['keepcopy'] = 'Conserver une copie du mail';
$labels['mailforward'] = 'Transfert de mail';
$labels['outofoffice'] = 'Notification d\'absence';
$labels['separate_alias'] = 'Séparer chaque adresse d\'alias par un point virgule';
$labels['separate_forward'] = 'Séparer chaque adresse de transfert par un point virgule';
$labels['success_changed'] = 'Configuration d\'absence enregistrée avec succès';
$labels['vacation'] = 'Absence';
// Button text
$labels['aliasesbutton'] = 'Récupérer les alias';
?>
