<?php
$labels = array();
$labels['aliases'] = 'Aliases';
$labels['autoreply'] = 'Verzend auto-reply naar afzender?';
$labels['autoreplybutton'] = 'Opslaan';
$labels['autoreplymessage'] = 'Auto-reply bericht';
$labels['autoreplysubject'] = 'Auto-reply onderwerp';
$labels['failed'] = 'Vakantie instelling mislukt!';
$labels['forwardingaddresses'] = 'Forwarding email adressen';
$labels['keepcopy'] = 'Bewaard een copy';
$labels['mailforward'] = 'Mail Forwarding';
$labels['outofoffice'] = 'Out-of-Office Notificatie';
$labels['separate_alias'] = 'Separate each alias address by a comma';
$labels['separate_forward'] = 'Separate each forward address by a comma';
$labels['success_disabled'] = 'Vakantie instelling succesvol uitgeschakeld';
$labels['success_enabled'] = 'Vakantie instelling succesvol ingeschakeld';
$labels['vacation'] = 'Auto-reply';
// Button text
$labels['aliasesbutton'] = 'Ophalen aliasen';
?>