<?php
$labels = array();
$labels['aliases'] = 'Alias';
$labels['autoreply'] = "Autoresposta Ativa ou Não";
$labels['autoreplybutton'] = 'Salvar';
$labels['autoreplymessage'] = 'Mensagem da autoresposta';
$labels['autoreplysubject'] = 'Assunto da autoresposta';
$labels['failed'] = 'Erro ao configurar autoresposta!';
$labels['forward'] = 'Configuração encaminahmento';
$labels['forwardingaddresses'] = 'Encaminhar para';
$labels['keepcopy'] = 'Manter uma cópoia ou não';
$labels['mailforward'] = 'Encaminhamento';
$labels['outofoffice'] = 'Autoresposta';
$labels['separate_alias'] = 'Separar os emails por vírgula';
$labels['separate_forward'] = 'Separar os emails por vírgula';
$labels['success_changed'] = 'Autoresposta auterado com suicesso';
$labels['vacation'] = 'Autoresposta';
// Button text
$labels['aliasesbutton'] = 'Coletar alias';
?>
