<?php
$labels = array();
$labels['vacation'] = 'В отпуске';
$labels['aliases'] = 'Адреса';
$labels['autoreply'] = "Посылать уведомление";
$labels['autoreplybutton'] = 'Сохранить';
$labels['autoreplymessage'] = 'Сообщение автоответа';
$labels['autoreplysubject'] = 'Тема автоответа';
$labels['failed'] = 'Ошибка при установке vacation!';
$labels['forward'] = 'Настройки перенаправления';
$labels['forwardingaddresses'] = 'Перенаправлять почту';
$labels['keepcopy'] = 'Оставлять копию сообщения';
$labels['mailforward'] = 'Перенаправление почты';
$labels['outofoffice'] = 'Уведомление В отпуске';
$labels['separate_alias'] = 'Разделяйте каждый адрес запятой';
$labels['separate_forward'] = 'Разделяйте каждый адрес перенаправления запятой';
$labels['success_changed'] = 'Настройки Vacation успешно изменены';
// Button text
$labels['aliasesbutton'] = 'Получить алиасы';
?>
