<?php
$labels = array();
$labels['aliases'] = 'Dodatni elektronski naslovi (aliasi) za odgovor';
$labels['autoreply'] = "Vključi samodejni odgovor";
$labels['autoreplybutton'] = 'Shrani';
$labels['autoreplymessage'] = 'Sporočilo samodejnega odgovora';
$labels['autoreplysubject'] = 'Zadeva samodejnega odgovora';
$labels['failed'] = 'Nastavitev odsotnosti je spodletelo!';
$labels['forward'] = 'Nastavitve posredovanja';
$labels['forwardingaddresses'] = 'Posreduj e-pošto na';
$labels['keepcopy'] = 'Shrani kopijo sporočila';
$labels['mailforward'] = 'Posredovanje e-pošte';
$labels['outofoffice'] = 'Odsotnost';
$labels['separate_alias'] = 'Ločite vsak elektronski naslov z vejico';
$labels['separate_forward'] = 'Ločite vsak elektronski naslov z vejico';
$labels['success_changed'] = 'Nastavitev odsotnosti je uspela';
$labels['vacation'] = 'Odsotnost';
// Button text
$labels['aliasesbutton'] = 'Pridobi aliase';
?>
